version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
        - es-data:/usr/share/elasticsearch/data
        - ./elasticsearch/config:/usr/share/elasticsearch/config
    ports:
        - 9200:9200
    expose:
        - 9300
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
        # https://github.com/docker-library/elasticsearch/issues/111
        # uliimit
    network_mode: "bridge"
  kibana:
    build: kibana
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601
    network_mode: "bridge"
  embulk:
    build: embulk
    links:
        - elasticsearch:elasticsearch
    volumes:
        - ./embulk/config:/opt/config
        - ./log:/opt/log
    network_mode: "bridge"
volumes:
    es-data:
        driver: local
networks:
  default:
    external:
      name: bridge
